apiVersion: v2
appVersion: v3.3.6
dependencies:
- condition: redis-ha.enabled
  name: redis-ha
  repository: https://dandydeveloper.github.io/charts/
  version: 4.34.11
description: Clustra Deploy, a Clustra-branded GitOps control plane based on Argo CD.
home: https://github.com/MahammadRafi06/clustra-platform
icon: https://raw.githubusercontent.com/MahammadRafi06/clustra-deploy/main/ui/src/assets/images/logo.png
keywords:
- argoproj
- clustra-deploy
- gitops
- clustra
kubeVersion: '>=1.25.0-0'
maintainers:
- name: clustra
  url: https://github.com/MahammadRafi06
name: clustra-deploy
sources:
- https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd
- https://github.com/argoproj/argo-cd
- https://github.com/MahammadRafi06/clustra-deploy
- https://github.com/MahammadRafi06/clustra-platform
version: 1.0.2
