server:
  extensions:
    enabled: true

platformExtensions:
  enabled: true
  items:
    - name: clustra-ai-service
      backend:
        services:
          - url: http://clustra-ai-service.argocd.svc:80
      ui:
        extensionUrl: https://github.com/MahammadRafi06/clustra-ai-service/releases/download/<release-tag>/extension.tar.gz
        checksumUrl: https://github.com/MahammadRafi06/clustra-ai-service/releases/download/<release-tag>/extension_checksums.txt
      rbac:
        allowRoles:
          - role:admin

    - name: model-cache
      backend:
        services:
          - url: http://model-cache-backend.model-cache.svc:80
      ui:
        extensionUrl: https://github.com/MahammadRafi06/clustra-modal-cache/releases/download/<release-tag>/extension.tar.gz
        checksumUrl: https://github.com/MahammadRafi06/clustra-modal-cache/releases/download/<release-tag>/extension_checksums.txt
      rbac:
        allowRoles:
          - role:admin
