name: Image

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  set-vars:
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    outputs:
      image-tag: ${{ steps.image.outputs.tag }}
      ghcr_image_name: ${{ steps.image.outputs.ghcr_image_name }}
      ghcr_repo: ${{ steps.image.outputs.ghcr_repo }}
      docker_image_name: ${{ steps.image.outputs.docker_image_name }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set image tag and names
        id: image
        run: |
          TAG="$(cat ./VERSION)-${GITHUB_SHA::8}"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          GHCR_NAMESPACE=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "ghcr_repo=ghcr.io/$GHCR_NAMESPACE" >> $GITHUB_OUTPUT
          echo "ghcr_image_name=ghcr.io/$GHCR_NAMESPACE:$TAG" >> $GITHUB_OUTPUT
          echo "docker_image_name=mahammadrafireesh/aiserv-argocd:$TAG" >> $GITHUB_OUTPUT

  build-and-publish:
    needs: [set-vars]
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/image-reuse.yaml
    with:
      ghcr_image_name: ${{ needs.set-vars.outputs.ghcr_image_name }}
      ghcr_cache_repo: ${{ needs.set-vars.outputs.ghcr_repo }}
      docker_image_name: ${{ needs.set-vars.outputs.docker_image_name }}
      go-version: 1.26.0
      platforms: linux/amd64,linux/arm64
      push: true
    secrets:
      ghcr_username: ${{ github.actor }}
      ghcr_password: ${{ secrets.GITHUB_TOKEN }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
